import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import { RandomFox } from '../components/RandomFox';

const Home: NextPage = () => {
  //vamos a obtener una foto aleatoria de una api con 123 fotos de zorros
  //generamos una función que nos devuelva un número aleatorio del 1 al 123:
  const random = (): number => {
    return Math.floor(Math.random() * 123) + 1;
  };

  //constantes que pasaremos al componente RandomFox por Props:

  //prop 1:
  //simulamos como vendrían los datos desde una api en la vida real, en formato array de objetos (con id, url...)
  //como no tenemos id, lo generamos:

  const generateId = (): string => {
    return Math.random().toString(36).substr(2, 9);
  };

  //establecemos nuestro tipado para cada objeto:

  type ImageType = { id: string; url: string };

  //creamos una variable de estado que tendrá un array de 4 objetos aleatorios
  //añadimos al estado <ImageType []> para asegurarnos que el seteo de la variable solo acepte array de objetos
  //que tengan nuestro tipado
  const [images, setImages] = useState<ImageType[]>([
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
  ]);

  //prop 2:
  const altImage: string = 'Fox image';

  return (
    <div>
      <Head>
        <title>App React with Typescript</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Foxes images</h1>
        {/* tomamos la variable de estado images (array de objetos) y renderizamos con un map 
        el componete RandomFox, al que pasamos props y daremos un padding de 4 (p-4) */}
        {images.map((image) => (
          <div key={image.id} className="p-4">
            <RandomFox image={image.url} alt={altImage} />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
